# Generated by Django 4.2.7 on 2024-05-16 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottoken',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bottoken',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
